<center><img src="https://i.imgur.com/zRrFdsf.png" width="700"></center>
PC2
Joaquin Alejandro Castro Villalba (20202114)

In [5]:
# Importamos la data de GidHub
import pandas as pd
datos = pd.read_excel('https://github.com/Control-ICDE/PC2/blob/main/HDI.xlsx?raw=true')
from tabulate import tabulate
print(datos)

         Back Table 1. Human Development Index and its components   \
0         NaN                                                NaN
1         NaN                                                NaN
2         NaN                                                NaN
3         NaN                                                NaN
4    HDI rank                                            Country
..        ...                                                ...
271       NaN                          Column 2: UNDESA (2022a).
272       NaN  Column 3: CEDLAS and World Bank (2022), ICF Ma...
273       NaN  Column 4: Barro and Lee (2018), ICF Macro Demo...
274       NaN  Column 5: IMF (2022), UNDESA (2022b), United N...
275       NaN  Column 6: Calculated based on data in columns ...

                         Unnamed: 2  Unnamed: 3                Unnamed: 4  \
0                               NaN         NaN                       NaN
1                               NaN         NaN                      SDG3
2                               NaN         NaN                       NaN
3    Human Development Index (HDI)          NaN  Life expectancy at birth
4                             Value         NaN                   (years)
..                              ...         ...                       ...
271                             NaN         NaN                       NaN
272                             NaN         NaN                       NaN
273                             NaN         NaN                       NaN
274                             NaN         NaN                       NaN
275                             NaN         NaN                       NaN

    Unnamed: 5                   Unnamed: 6 Unnamed: 7  \
0          NaN                          NaN        NaN
1          NaN                       SDG4.3        NaN
2          NaN                          NaN        NaN
3          NaN  Expected years of schooling        NaN
4          NaN                      (years)        NaN
..         ...                          ...        ...
271        NaN                          NaN        NaN
272        NaN                          NaN        NaN
273        NaN                          NaN        NaN
274        NaN                          NaN        NaN
275        NaN                          NaN        NaN

                  Unnamed: 8 Unnamed: 9  \
0                        NaN        NaN
1                     SDG4.4        NaN
2                        NaN        NaN
3    Mean years of schooling        NaN
4                    (years)        NaN
..                       ...        ...
271                      NaN        NaN
272                      NaN        NaN
273                      NaN        NaN
274                      NaN        NaN
275                      NaN        NaN

                                Unnamed: 10 Unnamed: 11  \
0                                       NaN         NaN
1                                    SDG8.5         NaN
2                                       NaN         NaN
3    Gross national income (GNI) per capita         NaN
4                              (2017 PPP $)         NaN
..                                      ...         ...
271                                     NaN         NaN
272                                     NaN         NaN
273                                     NaN         NaN
274                                     NaN         NaN
275                                     NaN         NaN

                            Unnamed: 12 Unnamed: 13 Unnamed: 14
0                                   NaN         NaN         NaN
1                                   NaN         NaN         NaN
2                                   NaN         NaN         NaN
3    GNI per capita rank minus HDI rank         NaN    HDI rank
4                                   NaN         NaN         NaN
..                                  ...         ...         ...
271                                 NaN         NaN         NaN
272                                 NaN         NaN         NaN
273                                 NaN         NaN         NaN
274                                 NaN         NaN         NaN
275                                 NaN         NaN         NaN

[276 rows x 15 columns]

In [6]:
# Eliminamos las cuatro primeras lienas de la tabla porque no tienen informacion
datos_limpios = datos.iloc[3:]
print(datos_limpios)

         Back Table 1. Human Development Index and its components   \
3         NaN                                                NaN
4    HDI rank                                            Country
5         NaN                                                NaN
6         NaN                        VERY HIGH HUMAN DEVELOPMENT
7           1                                        Switzerland
..        ...                                                ...
271       NaN                          Column 2: UNDESA (2022a).
272       NaN  Column 3: CEDLAS and World Bank (2022), ICF Ma...
273       NaN  Column 4: Barro and Lee (2018), ICF Macro Demo...
274       NaN  Column 5: IMF (2022), UNDESA (2022b), United N...
275       NaN  Column 6: Calculated based on data in columns ...

                         Unnamed: 2  Unnamed: 3                Unnamed: 4  \
3    Human Development Index (HDI)          NaN  Life expectancy at birth
4                             Value         NaN                   (years)
5                              2021         NaN                      2021
6                               NaN         NaN                       NaN
7                             0.962         NaN                   83.9872
..                              ...         ...                       ...
271                             NaN         NaN                       NaN
272                             NaN         NaN                       NaN
273                             NaN         NaN                       NaN
274                             NaN         NaN                       NaN
275                             NaN         NaN                       NaN

    Unnamed: 5                   Unnamed: 6 Unnamed: 7  \
3          NaN  Expected years of schooling        NaN
4          NaN                      (years)        NaN
5          NaN                         2021          a
6          NaN                          NaN        NaN
7          NaN                    16.500299        NaN
..         ...                          ...        ...
271        NaN                          NaN        NaN
272        NaN                          NaN        NaN
273        NaN                          NaN        NaN
274        NaN                          NaN        NaN
275        NaN                          NaN        NaN

                  Unnamed: 8 Unnamed: 9  \
3    Mean years of schooling        NaN
4                    (years)        NaN
5                       2021          a
6                        NaN        NaN
7                   13.85966        NaN
..                       ...        ...
271                      NaN        NaN
272                      NaN        NaN
273                      NaN        NaN
274                      NaN        NaN
275                      NaN        NaN

                                Unnamed: 10 Unnamed: 11  \
3    Gross national income (GNI) per capita         NaN
4                              (2017 PPP $)         NaN
5                                      2021         NaN
6                                       NaN         NaN
7                               66933.00454         NaN
..                                      ...         ...
271                                     NaN         NaN
272                                     NaN         NaN
273                                     NaN         NaN
274                                     NaN         NaN
275                                     NaN         NaN

                            Unnamed: 12 Unnamed: 13 Unnamed: 14
3    GNI per capita rank minus HDI rank         NaN    HDI rank
4                                   NaN         NaN         NaN
5                                  2021           b        2020
6                                   NaN         NaN         NaN
7                                     5         NaN           3
..                                  ...         ...         ...
271                                 NaN         NaN         NaN
272                                 NaN         NaN         NaN
273                                 NaN         NaN         NaN
274                                 NaN         NaN         NaN
275                                 NaN         NaN         NaN

[273 rows x 15 columns]

In [7]:
#Conservamos las dos primeras columnas que comienzan con NaN
colum_mantener = datos_limpios.columns[:2]
columnas_no_nan = datos_limpios.loc[:, datos_limpios.iloc[0].notna()].iloc[:, 2:]
datos_finales = pd.concat([datos_limpios[colum_mantener], columnas_no_nan], axis=1)
print(datos_finales)

         Back Table 1. Human Development Index and its components   \
3         NaN                                                NaN
4    HDI rank                                            Country
5         NaN                                                NaN
6         NaN                        VERY HIGH HUMAN DEVELOPMENT
7           1                                        Switzerland
..        ...                                                ...
271       NaN                          Column 2: UNDESA (2022a).
272       NaN  Column 3: CEDLAS and World Bank (2022), ICF Ma...
273       NaN  Column 4: Barro and Lee (2018), ICF Macro Demo...
274       NaN  Column 5: IMF (2022), UNDESA (2022b), United N...
275       NaN  Column 6: Calculated based on data in columns ...

                      Unnamed: 6               Unnamed: 8  \
3    Expected years of schooling  Mean years of schooling
4                        (years)                  (years)
5                           2021                     2021
6                            NaN                      NaN
7                      16.500299                 13.85966
..                           ...                      ...
271                          NaN                      NaN
272                          NaN                      NaN
273                          NaN                      NaN
274                          NaN                      NaN
275                          NaN                      NaN

                                Unnamed: 10  \
3    Gross national income (GNI) per capita
4                              (2017 PPP $)
5                                      2021
6                                       NaN
7                               66933.00454
..                                      ...
271                                     NaN
272                                     NaN
273                                     NaN
274                                     NaN
275                                     NaN

                            Unnamed: 12 Unnamed: 14
3    GNI per capita rank minus HDI rank    HDI rank
4                                   NaN         NaN
5                                  2021        2020
6                                   NaN         NaN
7                                     5           3
..                                  ...         ...
271                                 NaN         NaN
272                                 NaN         NaN
273                                 NaN         NaN
274                                 NaN         NaN
275                                 NaN         NaN

[273 rows x 7 columns]

In [8]:
# Ahora, borramos las filas con puro NaN como valor a execcion de la segunda fila
datos_limpios = datos_finales[~(datos_finales.iloc[:, 2:].isna().all(axis=1) & datos_finales.iloc[:, 1].notna())]
print(datos_limpios)

         Back Table 1. Human Development Index and its components   \
3         NaN                                                NaN
4    HDI rank                                            Country
5         NaN                                                NaN
7           1                                        Switzerland
8           2                                             Norway
..        ...                                                ...
228       NaN                                              World
229       NaN                                                NaN
258       NaN                                                NaN
259       NaN                                                NaN
268       NaN                                                NaN

                      Unnamed: 6               Unnamed: 8  \
3    Expected years of schooling  Mean years of schooling
4                        (years)                  (years)
5                           2021                     2021
7                      16.500299                 13.85966
8                        18.1852                 13.00363
..                           ...                      ...
228                    12.780907                 8.617461
229                          NaN                      NaN
258                          NaN                      NaN
259                          NaN                      NaN
268                          NaN                      NaN

                                Unnamed: 10  \
3    Gross national income (GNI) per capita
4                              (2017 PPP $)
5                                      2021
7                               66933.00454
8                               64660.10622
..                                      ...
228                            16752.082922
229                                     NaN
258                                     NaN
259                                     NaN
268                                     NaN

                            Unnamed: 12 Unnamed: 14
3    GNI per capita rank minus HDI rank    HDI rank
4                                   NaN         NaN
5                                  2021        2020
7                                     5           3
8                                     6           1
..                                  ...         ...
228                                   —           —
229                                 NaN         NaN
258                                 NaN         NaN
259                                 NaN         NaN
268                                 NaN         NaN

[223 rows x 7 columns]

In [9]:
# A continuacion, eliminaremos las filas que tengan puro NaN
datos_limpios = datos_limpios.dropna(how='all')
print(datos_limpios)

         Back Table 1. Human Development Index and its components   \
3         NaN                                                NaN
4    HDI rank                                            Country
5         NaN                                                NaN
7           1                                        Switzerland
8           2                                             Norway
..        ...                                                ...
221       NaN                                 Sub-Saharan Africa
223       NaN                          Least developed countries
224       NaN                     Small island developing states
226       NaN  Organisation for Economic Co-operation and Dev...
228       NaN                                              World

                      Unnamed: 6               Unnamed: 8  \
3    Expected years of schooling  Mean years of schooling
4                        (years)                  (years)
5                           2021                     2021
7                      16.500299                 13.85966
8                        18.1852                 13.00363
..                           ...                      ...
221                    10.267338                 6.001639
223                    10.182659                  5.21532
224                    12.422289                  9.08964
226                    16.459253                12.267755
228                    12.780907                 8.617461

                                Unnamed: 10  \
3    Gross national income (GNI) per capita
4                              (2017 PPP $)
5                                      2021
7                               66933.00454
8                               64660.10622
..                                      ...
221                             3698.868914
223                             2880.652487
224                            16782.329527
226                            45086.969067
228                            16752.082922

                            Unnamed: 12 Unnamed: 14
3    GNI per capita rank minus HDI rank    HDI rank
4                                   NaN         NaN
5                                  2021        2020
7                                     5           3
8                                     6           1
..                                  ...         ...
221                                   —           —
223                                   —           —
224                                   —           —
226                                   —           —
228                                   —           —

[213 rows x 7 columns]

In [10]:
#Ahora, dejamos en blanco todas las celdas con NaN y tambien los que tengan ".." y "-"
datos_limpios = datos_limpios.fillna('')
datos_limpios = datos_limpios.replace({'..': '', '—': ''})
datos_limpios

,Back,Table 1. Human Development Index and its components,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14
3,,,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
4,HDI rank,Country,(years),(years),(2017 PPP $),,
5,,,2021,2021,2021,2021,2020
7,1,Switzerland,16.500299,13.85966,66933.00454,5,3
8,2,Norway,18.1852,13.00363,64660.10622,6,1
...,...,...,...,...,...,...,...
221,,Sub-Saharan Africa,10.267338,6.001639,3698.868914,,
223,,Least developed countries,10.182659,5.21532,2880.652487,,
224,,Small island developing states,12.422289,9.08964,16782.329527,,
226,,Organisation for Economic Co-operation and Dev...,16.459253,12.267755,45086.969067,,
228,,World,12.780907,8.617461,16752.082922,,

Profesor, le menciono mi caso que el Jupyter no ejecuta en mi computadora y me comento que le enviara el enlace del GidHub con el trabajo.

A continuacion, le presento el proceso que se tendria que seguir para crear la pagina web

1. El archivo con el codigo debe de nombrarse como "index".
2. A continuacion, en la web de GidHub vamos al apartado de "Settings" y luego en "Pages"
3. Seguido de ello, en la opcion de "branch" seleccionamos "main" y posteriormente "save"
4. Luego de esperar unos minutos aparecera el link de la pagina web.**texto en negrita**